version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=file:./prod.db
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8080}
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
