version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=development
      - JWT_SECRET=dev-secret-key
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
